/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package control_conciertos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Nicoleta
 */
public class VistaConcierto extends javax.swing.JFrame {

   
    
  
    /**
     * Vista del proyecto
     */
    public VistaConcierto() {
        initComponents();
        
     
         
    }
        /* manejadorVentana Co = new manejadorVentana();
         manejadorComponentes Con = new manejadorComponentes();
         this.addComponentListener (Con);
         this.addWindowListener(Co);
        
         manejadorClicks CClick = new manejadorClicks();
         btnAceptar.addActionListener(CClick);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ENTRADA");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
/*
class manejadorClicks  implements ActionListener{

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println(e.getActionCommand()); 
        System.out.println("Se ha pulsado el boton ");
    }
    
}
class manejadorComponentes implements ComponentListener{

    @Override
    public void componentResized(ComponentEvent e) {
        System.out.println("Cambia tamaño");
    }

   
    @Override
    public void componentMoved(ComponentEvent e) {
        System.out.println("Se ha movido");
    }


    @Override
    public void componentShown(ComponentEvent e) {
        System.out.println("Se muestra los componentes");
    }

    @Override
    public void componentHidden(ComponentEvent e) {
        System.out.println("Se ha ocultado");
    }
    
}
class manejadorVentana implements WindowListener{

    @Override
    public void windowOpened(WindowEvent e) {
        System.out.println("Se abre la ventana");
    }

    @Override
    public void windowClosing(WindowEvent e) {
        System.out.println("Cerrando la ventana");
    }

    @Override
    public void windowClosed(WindowEvent e) {
        System.out.println("Cerrado");
    }

    @Override
    public void windowIconified(WindowEvent e) {
        System.out.println("Se ha iconizando");
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
       System.out.println("Se ha deziconizando");
    }

    @Override
    public void windowActivated(WindowEvent e) {
        System.out.println("Se activa la ventana");
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        System.out.println("Se ha desactivado la ventana");
    }

}*/