/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package control_conciertos;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 *
 * @author Nicoleta
 */
public class VistaConcierto extends javax.swing.JFrame {

    /**
     * Vista del proyecto
     */
    public VistaConcierto() {
        initComponents();
    }
        /* manejadorVentana Co = new manejadorVentana();
         manejadorComponentes Con = new manejadorComponentes();
         this.addComponentListener (Con);
         this.addWindowListener(Co);
        
         manejadorClicks CClick = new manejadorClicks();
         btnAceptar.addActionListener(CClick);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FotoPagina = new javax.swing.JLabel();
        TituloEntrada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FotoPagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Diseño sin título.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FotoPagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FotoPagina, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        TituloEntrada.setBackground(new java.awt.Color(139, 179, 204));
        TituloEntrada.setFont(new java.awt.Font("Scheherazade", 3, 36)); // NOI18N
        TituloEntrada.setForeground(new java.awt.Color(0, 0, 204));
        TituloEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloEntrada.setText("Pilla Tu Entrada");
        TituloEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 1, true));
        TituloEntrada.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(TituloEntrada, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoPagina;
    private javax.swing.JLabel TituloEntrada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
/*
class manejadorClicks  implements ActionListener{

    @Override
    public void actionPerformed(ActionEvent e) {
        System.out.println(e.getActionCommand()); 
        System.out.println("Se ha pulsado el boton ");
    }
    
}
class manejadorComponentes implements ComponentListener{

    @Override
    public void componentResized(ComponentEvent e) {
        System.out.println("Cambia tamaño");
    }

   
    @Override
    public void componentMoved(ComponentEvent e) {
        System.out.println("Se ha movido");
    }


    @Override
    public void componentShown(ComponentEvent e) {
        System.out.println("Se muestra los componentes");
    }

    @Override
    public void componentHidden(ComponentEvent e) {
        System.out.println("Se ha ocultado");
    }
    
}
class manejadorVentana implements WindowListener{

    @Override
    public void windowOpened(WindowEvent e) {
        System.out.println("Se abre la ventana");
    }

    @Override
    public void windowClosing(WindowEvent e) {
        System.out.println("Cerrando la ventana");
    }

    @Override
    public void windowClosed(WindowEvent e) {
        System.out.println("Cerrado");
    }

    @Override
    public void windowIconified(WindowEvent e) {
        System.out.println("Se ha iconizando");
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
       System.out.println("Se ha deziconizando");
    }

    @Override
    public void windowActivated(WindowEvent e) {
        System.out.println("Se activa la ventana");
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        System.out.println("Se ha desactivado la ventana");
    }

}*/